version: '3'
services:
  web:
    image: nginx:1.19.6-alpine
    ports:
      - 8880:80
    volumes:
      - "./src:/var/www/chess"
      - "./docker/site.conf:/etc/nginx/conf.d/default.conf"
    working_dir: "/var/www/chess"
    depends_on:
      - php

  php:
    image: php:7.4-fpm
    volumes:
      - "./src:/var/www/chess"
    working_dir: "/var/www/chess"